### ISSUE TITLE
Asus ROG Strix X570-I Gaming Motherboard - LAN is working without any connection dropped [v5.11-mb]

### ISSUE THREAD

**Issue by mdangc** [donatengit/AppleIGB#16]
I got the LAN working yesterday consistently without any internet being dropped. The kext I used is the latest pre-release: 

[v5.11-mb](https://github.com/donatengit/AppleIGB/tree/v5.11-mb)

I tested out with downloading a torrent successfully. MacOS has been running stable internet connection for more than 45 minutes compared to previous time when it will drop the connection after 15 minutes. 

What did yesterday was updated Opencore and config.plist to the latest release with every single kexts to their latest version. 

However, one particular strange thing I did noticed that will break the internet connection is when I ran the Geekbench benchmark, the app tried to upload results to their site. The internet connection will stopped working. This issue has been happening before with every versions of AppleIGB until now. It's a minor issue but worth mentioning regardless. 

My system:

Asus ROG Strix X570-I Gaming Motherboard - Mini ITX
Intel I211-AT - LAN from the Motherboard without any dongle 
AMD Ryzen 9 5900X
AMD Radeon 5700XT - Anniversary Edition 
G-Skill Neo - 32GB RAM
Opencore 0.8.5
Every kexts is updated to their latest version 

Wifi - working 
Bluetooth - working 
LAN - working

**Comment by donatengit** [comment]
Hey @mdangc 

Great, thanks for testing! Is it still working without issues on the long run?

**Comment by donatengit** [comment]
This fork is deprecated, see [README](https://github.com/donatengit/AppleIGB) for better option of the driver
