### ISSUE TITLE
Asus Pro WS X570-ACE - Mostly working with v5.11.4

### ISSUE THREAD

**Issue by pixlfixer** [donatengit/AppleIGB#17]
Mobo: Asus Pro WS X570-ACE
CPU: 3900x
OS: Monterey 12.6
OC 8.3 (with latest kexts)

Still early, but this solved an extremely annoying issue I was having with Adobe Lightroom. Newer versions of LR wouldn't work with my USB ethernet dongle. After about an hour with this driver, I lost connection, but changing speed in network settings to 1000baseT brought it back. Fast.com says Im getting 1.2Gbps :)

I am so incredibly grateful for all your work on this driver! Thank you, thank you, thank you!

edit: having relatively frequent lost connections. Switching the network speed from 1000 to 100 and back 1000baseT gets it working again. Does anyone have a quick / easy script to automate this toggle?

**Comment by Lorys89** [comment]
try this 
[AppleIGB.kext-max mod.zip](https://github.com/donatengit/AppleIGB/files/9930365/AppleIGB.kext-max.mod.zip)

**Comment by donatengit** [comment]
@pixlfixer thanks for testing!

Unfortunately this fork is being deprecated, see [README](https://github.com/donatengit/AppleIGB) for better option of the driver.
