### ISSUE TITLE
X570 and  I211AT packet loss after a few minutes of use

### ISSUE THREAD

**Issue by MrJiang1106** [donatengit/AppleIGB#18]
hello developer
I have a problem with my configuration using the AppleIGB to drive the I211AT
It will fail to connect to the Internet a few minutes after it is turned on and used. In the first few minutes, everything is normal, and the network speed can run to 1000Mbps, but after a few minutes, it cannot connect to the Internet directly.
After testing, I disable the Ethernet and use the WiFi card AX200 and everything works fine, this should be the problem of the Ethernet driver AppleIGB
I disable and re-enable ethernet and he works fine again but after a few minutes it loses packets again

My computer equipment is as follows：

System: MacOS Monterey 12.6
Processor: AMD 5900X
Motherboard: ASRock X570 Phantom Gaming 4
Ethernet Card: Realtek I211AT
WiFi card: Intel AX200
AppleIGB: v5.11.4 (currently v5.11.4 Oct 6 release, but all versions from v5.72 Feb 4 to v5.11.4 Oct 6 have been tested with problems, versions before v5.72 Feb 4 are not tested)
Airportltlwm: v2.2.0
Opencore: v0.8.6

**Comment by donatengit** [comment]
@MrJiang1106 
Thanks for testing, this fork is being deprecated, please check [README](https://github.com/donatengit/AppleIGB) for better option of the driver.
