### ISSUE TITLE
Working b450 MSI Pro Carbon 

### ISSUE THREAD

**Issue by sharklatan** [donatengit/AppleIGB#5]
Bus:	PCI
  ID del fabricante:	0x8086
  ID del dispositivo:	0x1539
  ID del fabricante del subsistema:	0x1462
  ID del subsistema:	0x7b85
  ID de la revisión:	0x0003
  Velocidad del enlace PCIe:	2.5 GT/s
  Ancho del enlace PCIe:	x1
  Driver:	com.amdosx.driver.AppleIGB
  Nombre del dispositivo BSD:	en0
  Dirección MAC:	00:d8:61:xx:xx:xx
  Soporte para AVB:	No
  Velocidad máxima del enlace:	1 Gb/s

![98391FD3-2D70-4021-B778-38FE0A670C0C](https://user-images.githubusercontent.com/5210221/160517130-cc898897-dc23-46cc-8852-182b90a4052e.jpeg)

**Comment by donatengit** [comment]
This fork is deprecated, see [README](https://github.com/donatengit/AppleIGB) for better option of the driver
